services:
    database:
        image: postgres:latest
        container_name: barber-db
        restart: always
        networks:
            - app_network
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DB_NAME}
        ports:
            - "5434:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
    api:
        container_name: barber-api
        build: .
        env_file: .env
        networks:
            - app_network
        links:
            - database
        depends_on:
            database:
                condition: service_healthy
        ports:
            - "${PORT}:3333"
networks:
    app_network:
        name: app_network
        driver: bridge